### ISSUE TITLE
Fix IT Bot

### ISSUE THREAD

**Issue by AshutoshGoswami24** [LISA-KOREA/UPLOADER-BOT-V4#15]
2024-06-02 03:44:40,301 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'yt-dlp'
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspaces/AllSaveBot_V3.0/plugins/echo.py", line 129, in echo
    process = await asyncio.create_subprocess_exec(
  File "/home/codespace/.python/current/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/home/codespace/.python/current/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/home/codespace/.python/current/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/home/codespace/.python/current/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/home/codespace/.python/current/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp'

**Comment by LISA-KOREA** [comment]
You update the repo
